#include <iostream>
#include <fstream>
#include <string>
using namespace std;
const int MAX = 50; // 어디서든 써야해서 DocWriter.h 에 넣는게 가장 좋다.
class DocWriter {
protected:
	char fileName[MAX];
	string content;
public:
	DocWriter();
	DocWriter(const char* fileName, const string& content);
	DocWriter(const DocWriter& obj); // 복사생성자
	~DocWriter();
	void setFileName(const char* fileName);
	void setContent(const string& content);
	void Write();
};
DocWriter::DocWriter() {
	cout << "Doc:인자 없는 생성자" << endl;
	strcpy_s(this->fileName, MAX, "noName.txt");
	this->content = "There is no content.";
}
DocWriter::DocWriter(const char* fileName, const string& content) {
	cout << "Doc:인자 있는 생성자" << endl;
	strcpy_s(this->fileName, MAX, fileName);
	this->content = content;
}
DocWriter::DocWriter(const DocWriter& obj) {
	cout << "Doc:복사 생성자" << endl;
	strcpy_s(this->fileName, MAX, obj.fileName);
	this->content = obj.content;
}
DocWriter::~DocWriter() {
	cout << "Doc:소멸자" << endl;
}
void DocWriter::setFileName(const char* fileName) {
	strcpy_s(this->fileName, MAX, fileName);
}
void DocWriter::setContent(const string& content) {
	this->content = content;
}
void DocWriter::Write() {
	ofstream fout;
	fout.open(this->fileName);
	if (!fout) {
		cout << "Error: " << this->fileName << " 열 수 없음" << endl;
		return;
	}
	fout << "# CONTENT #" << endl << endl;
	fout << this->content;
	fout.close();
}
class HTMLWriter :public DocWriter {
protected:
	char fontName[MAX];
	char fontColor[MAX];
	int fontSize;
public:
	HTMLWriter();
	HTMLWriter(const char* fileName, const string& content,
		const char* fontName, const char* fontColor, int fontSize);
	HTMLWriter(const HTMLWriter& obj);
	~HTMLWriter();
	void Write();
	void SetFont(const char* fontName, const char* fontColor, int fontSize);
};
HTMLWriter::HTMLWriter()
	:DocWriter()
{
	cout << "HTML: 인자 없는 생성자" << endl;
	strcpy_s(this->fileName, MAX, "noName.html");
	strcpy_s(this->fontName, MAX, "궁서");
	strcpy_s(this->fontColor, MAX, "Red");
	this->fontSize = 3;
}
HTMLWriter::HTMLWriter(const char* fileName, const string& content,
	const char* fontName, const char* fontColor, int fontSize)
	:DocWriter(fileName, content)
{
	cout << "HTML: 인자 있는 생성자" << endl;
	strcpy_s(this->fontName, strlen(fontName) + 1, fontName);
	strcpy_s(this->fontColor, strlen(fontColor) + 1, fontColor);
	this->fontSize = fontSize;
}
HTMLWriter::HTMLWriter(const HTMLWriter& obj) {
	cout << "HTML: 복사 생성자" << endl;
}
HTMLWriter::~HTMLWriter() {
	cout << "HTML: 소멸자" << endl;
}
void HTMLWriter::Write() {
	ofstream fout;
	fout.open(this->fileName);
	if (!fout) {
		cout << "Error: " << this->fileName << " 열 수 없음" << endl;
		return;
	}
	fout << "<HTML><HEAD><TITLE>";
	fout << "This document was generated by HTMLWriter";
	fout << "</TITLE></HEAD><BODY>";
	fout << "<H1>Content</H1>";

	fout << "<Font name='" << this->fontName << "'";
	fout << " size='" << this->fontSize << "'";
	fout << " color='" << this->fontColor << "'>";

	fout << this->content;

	fout << "</Font>";

	fout << "</BODY></HTML>";
}
void HTMLWriter::SetFont(const char* fontName, const char* fontColor, int fontSize) {
	strcpy_s(this->fontName, strlen(fontName) + 1, fontName);
	strcpy_s(this->fontColor, strlen(fontColor) + 1, fontColor);
	this->fontSize = fontSize;
}
int main() {
	/*DocWriter d1;
	d1.Write();
	DocWriter d2("foo.txt", "You must be a good programmer!\nMidTerm3 공부합시다!");
	d2.Write();*/

	HTMLWriter h1;
	h1.Write();
	HTMLWriter h2
	("foo.html",
		"You must be a good programmer!\nMidTerm3 공부합시다!",
		"Arial", "green", 3);
	h2.Write();

	return 0;
}